### ISSUE TITLE
商丘疫情防控码？

### ISSUE THREAD

**Issue by chenbo-again** [Yidadaa/Real-Qingshui-Pass#1]

**Comment by Yidadaa** [comment]
为了规避风险，屏蔽了原来的路由，想用的话自己 fork 一份改一下吧，就只需要改一个地方：https://github.com/Yidadaa/Real-Qingshui-Pass/blob/7947ed125d5c64b3c5491757873229f24a46b4a0/src/components/ScanPage.vue#L64

改成 `/login` 即可。
