### ISSUE TITLE
弹窗提示：摄像头打开错误

### ISSUE THREAD

**Issue by finlater** [Yidadaa/Real-Qingshui-Pass#2]
`npm run build`之后，在本地浏览器打开`dist`中的文件可以正常打开摄像头，但是一旦把`dist`部署到云上的nginx服务器后，远程访问就提示摄像头打开错误：
![image](https://user-images.githubusercontent.com/39994066/156876776-cd069d25-2f54-4666-93f9-bb03f6e2ac53.png)

😭

**Comment by Yidadaa** [comment]
请务必确保启用了 https，浏览器安全策略限制了摄像头权限仅能在 https 域名下正常申请。

**Comment by finlater** [comment]
解决了，多谢大佬！ 👍🏻

**Comment by finlater** [comment]
顺便再请问一下 每次默认都是入校，出校除了手动替换文字是还有其它隐藏的切换方法吗

**Comment by Yidadaa** [comment]
通过 url 参数区分：
入校：https://your-domain/#/home?type=in
出校：https://your-domain/#/home?type=out
